import { getMuxPlaybackId } from "@/app/mux";

export type ProjectDetail = {
  id: string;
  title: string;
  description: string;
  category: string;
  status: string;
  client: string;
  year: string;
  visit: string;
  deliverables: string;
  image?: string;
  /** Public Mux playback ID. */
  video?: string;
  alt: string;
};

export const projects: ProjectDetail[] = [
  {
    id: "Melabody",
    title: "Melabody",
    description: "A bold launch system for a next-generation creative tool",
    category: "Fashion & Beauty",
    image: "/images/melabody.avif",
    alt: "Orbit project",
    status: "Ongoing",
    year: "2026",
    deliverables: "Strategy, Brand, Experience",
        client: "Melabody Inc",
    visit: "https://melabody.fyi",
    
  },
  {
    id: "Rhode",
    title: "Rhode",
    description: "A visual identity for a studio making everyday objects",
    category: "Fashion & Beauty",
    video: getMuxPlaybackId("rhode"),
    alt: "Still Life project",
    status: "Ongoing",
    year: "2026",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://rode.com",
  },
  {
    id: "Beanos_Cafe",
    title: "Beano's Cafe",
    description: "A digital-first identity for a fast-growing skincare label",
    category: "Food & Drinks",
    image: "/images/Beano.avif",
    alt: "Luma project",
    status: "Ongoing",
    year: "2026",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://beanos.com",
  },

  {
    id: "Redline",
    title: "Redline",
    description:
      "A collaborative identity for a sustainable textile collective",
    category: "Sport & Cycling",
    image: "/markus-spiske-HYUXBWVyh14-unsplash.avif",
    alt: "Common Thread project",
    status: "Coming soon",
    year: "S 2026",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://redline.com",
  },
  {
    id: "Unna",
    title: "Unna",
    description: "A fresh visual language for a coastal food journal",
    category: "Fitness",
    video: getMuxPlaybackId("unna"),
    alt: "Onda project",
    status: "Coming soon",
    year: "S 2027",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://unna.com",
  },
  {
    id: "Tallow",
    title: "Tallow",
    description: "A warm editorial platform for contemporary African interiors",
    category: "Finance",
    image: "/images/talow.avif",
    alt: "Moya House project",
    status: "Complete",
    year: "2026",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://tallow.com",
  },
  {
    id: "Ilia",
    title: "Ilia",
    description: "A digital-first identity for a fast-growing skincare label",
    category: "Beauty",
    image: "/images/ilia.avif",
    alt: "Luma project",
    status: "Complete",
    year: "2026",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://ilia.com",
  },
  {
    id: "Vanta",
    title: "Vanta",
    description: "A playful commerce experience for a modern flower studio",
    category: "Finance",
    image: "/K1z8mV8TAFVjZBpOYWvGpV130Kw.avif",
    video: getMuxPlaybackId("vanta"),
    alt: "Aster project",
    status: "Complete",
    year: "2025",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://vanta.com",
  },
  {
    id: "Just_Do_It",
    title: "Just Do It",
    description: "A global campaign built around movement and possibility",
    category: "Sports",
    image: "/images/jdi.avif",
    alt: "Just Do It project",
    status: "Complete",
    year: "2025",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://nike.com",
  },
  {
    id: "Hearth",
    title: "Hearth",
    description: "A global campaign built around movement and possibility",
    category: "Sports",
    image: "/images/suvI3NLr8X1VCgPDJ5pLgxWxU.avif",
    alt: "Hearth project",
    status: "Complete",
    year: "2025",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://hearth.cyi",
  },
  {
    id: "Dua",
    title: "Dua",
    description: "A campaign-led rebrand for a contemporary fashion label",
    category: "Fashion & Beauty",
    image: "/gylain-omer-SEHB67NK4Wg-unsplash.avif",
    video: getMuxPlaybackId("dua"),
    alt: "Cinder project",
    status: "Complete",
    year: "2024",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://dua.com",
  },
  {
    id: "eWay",
    title: "eWay",
    description: "An atmospheric campaign for a new independent film festival",
    category: "Travel",
    video: getMuxPlaybackId("eWay"),
    alt: "Afterglow project",
    status: "Complete",
    year: "2023",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
      visit: "https://eway.fyi",
  },
  {
    id: "echelon",
    title: "Echelon",
    description: "An atmospheric campaign for a new independent film festival",
    category: "Sport",
    image: "/images/echelon.avif",
    alt: "Echelon project",
    status: "Complete",
    year: "2023",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
      visit: "https://echelon.fyi",
  },
  {
    id: "Porsce_911",
    title: "Porsce 911",
    description: "A digital-first identity for a fast-growing skincare label",
    category: "Sport & Cars",
    image: "/suvI3NLr8X1VCgPDJ5pLgxWxU.avif",
    video: getMuxPlaybackId("porsce911"),
    alt: "Luma project",
    status: "Concept",
    year: "2026",
    deliverables: "Strategy, Brand, Experience",
      client: "Client Inc",
    visit: "https://porsce.com",
  },
  {
    id: "Nothing_Ear_3",
    title: "Nothing Ear 3",
    description: "A visual identity for a studio making everyday objects",
    category: "Technology",
    video: getMuxPlaybackId("nothingEar3"),
    alt: "Still Life project",
    status: "Concept",
    year: "2025",
    deliverables: "Strategy, Brand, Experience",
      client: "Nothing Inc",
    visit: "https://nothing.com",
  },
  {
    id: "Kunye",
    title: "Kunye",
    description: "A visual identity for a studio making everyday objects",
    category: "Entertainment",
    video: getMuxPlaybackId("kunye"),
    alt: "Still Life project",
    status: "Concept",
    year: "2025",
    deliverables: "Strategy, Brand, Experience",
      client: "Shimza",
    visit: "https://kunye.com",
  },
  {
    id: "Honorable",
    title: "Honorable",
    description: "A visual identity for a studio making everyday objects",
    category: "Entertainment",
    video: getMuxPlaybackId("honorable"),
    alt: "Still Life project",
    status: "Concept",
    year: "2025",
    deliverables: "Strategy, Brand, Experience",
      client: " Honorable Inc",
    visit: "https://honorable.com",
  },
];

export const getProjectById = (projectId: string | string[] | undefined) => {
  const normalizedId = Array.isArray(projectId) ? projectId[0] : projectId;
  if (!normalizedId) return undefined;

  return projects.find(
    (project) => project.id.toLowerCase() === normalizedId.toLowerCase(),
  );
};
